
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('IN', 'INDIA');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('UK', 'UK');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('US', 'United States of America');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('AU', 'Australia');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('DE', 'Germany');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('BE', 'Belgium');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('FR', 'France');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('CH', 'Switzerland');
INSERT INTO COUNTRY (COUNTRYISO, COUNTRY_NAME)  VALUES ('NL', 'Netherlands')